### ISSUE TITLE
Error in the multiprocessing-update?

### ISSUE THREAD

**Issue by toreog** [Brandon-Rozek/vspursuer#26]
I think there is a bug in the multiprocessing-updated version of vsp:

./vspursuer.py -i ./examples/R6     
Parsed 27 matrices
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/mctore/vspursuer/vsp.py", line 106, in has_vsp
    impfunction = interpretation[Implication]
                  ~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: <logic.Operation object at 0x10a36ef00>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mctore/vspursuer/./vspursuer.py", line 35, in <module>
    vsp_result: VSP_Result = result.get()
                             ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
KeyError: <logic.Operation object at 0x105a4fce0>

**Comment by Brandon-Rozek** [comment]
Hi Tore! Thanks for the bug report. Unfortunately I cannot reproduce your issue on my machine, can you tell me the exact version of Python you're running?

```bash
python --version
```

**Comment by toreog** [comment]
Hi Brandon!

Thank you for replying! I was using 3.12, but have now upgraded to 3.13.1. However, I still get the same output. I'm sorry for troubling you with this!

Best,
Tore

**Comment by Brandon-Rozek** [comment]
I was able to reproduce this issue on Windows 11. One step closer to a fix :)

**Comment by Brandon-Rozek** [comment]
I fixed the issue I identified with how multiprocessing was working in Windows. If you still have the problem after updating, feel free to re-open this issue with any updated error messages.

**Comment by toreog** [comment]
You rock, Brandon! Thank you so much!!
